// <auto-generated />
using System;
using Am.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Am.Infrastructure.Migrations
{
    [DbContext(typeof(AmContext))]
    [Migration("20260506113423_AddPositionToCategory")]
    partial class AddPositionToCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Am.ApplicationCore.Domain.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasColumnType("text")
                        .HasColumnName("adresse");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_creation");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Identifiant")
                        .HasColumnType("text")
                        .HasColumnName("identifiant");

                    b.Property<string>("Nom")
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Prenom")
                        .HasColumnType("text")
                        .HasColumnName("prenom");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.CBDash", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<int>("SocieteId")
                        .HasColumnType("integer")
                        .HasColumnName("societe_id");

                    b.Property<string>("SousCategory")
                        .HasColumnType("text")
                        .HasColumnName("sous_category");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("SocieteId");

                    b.ToTable("CBDashes");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.CR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Annee")
                        .HasColumnType("integer")
                        .HasColumnName("annee");

                    b.Property<double>("MontantConsomme")
                        .HasColumnType("double precision")
                        .HasColumnName("montant_consomme");

                    b.Property<int?>("ProduitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProduitId");

                    b.ToTable("CRs");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.CategorieCR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<int>("RapportFinancierId")
                        .HasColumnType("integer")
                        .HasColumnName("rapport_financier_id");

                    b.HasKey("Id");

                    b.HasIndex("RapportFinancierId");

                    b.ToTable("CategoriesCR");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.CategorieFinanciere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.Property<int>("RapportFinancierId")
                        .HasColumnType("integer")
                        .HasColumnName("rapport_financier_id");

                    b.HasKey("Id");

                    b.HasIndex("RapportFinancierId");

                    b.ToTable("CategoriesFinancieres");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.ClesDeRepartition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("ClesCoutFixes")
                        .HasColumnType("double precision")
                        .HasColumnName("cles_cout_fixes");

                    b.Property<string>("Mois")
                        .HasColumnType("text")
                        .HasColumnName("mois");

                    b.Property<double>("SaisonaliteCA")
                        .HasColumnType("double precision")
                        .HasColumnName("saisonalite_ca");

                    b.Property<double>("SaisonalitePoids")
                        .HasColumnType("double precision")
                        .HasColumnName("saisonalite_poids");

                    b.Property<int>("SocieteId")
                        .HasColumnType("integer")
                        .HasColumnName("societe_id");

                    b.HasKey("Id");

                    b.HasIndex("SocieteId");

                    b.ToTable("ClesDeRepartitions");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.CountDash", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Couleur")
                        .HasColumnType("text")
                        .HasColumnName("couleur");

                    b.Property<string>("NomEntity")
                        .HasColumnType("text")
                        .HasColumnName("nom_entity");

                    b.Property<int>("SocieteId")
                        .HasColumnType("integer")
                        .HasColumnName("societe_id");

                    b.HasKey("Id");

                    b.HasIndex("SocieteId");

                    b.ToTable("CountDashes");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.CourbDash", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Rapport1")
                        .HasColumnType("text")
                        .HasColumnName("rapport1");

                    b.Property<string>("Rapport2")
                        .HasColumnType("text")
                        .HasColumnName("rapport2");

                    b.Property<int>("SocieteId")
                        .HasColumnType("integer")
                        .HasColumnName("societe_id");

                    b.Property<string>("SousCategory")
                        .HasColumnType("text")
                        .HasColumnName("sous_category");

                    b.HasKey("Id");

                    b.HasIndex("SocieteId");

                    b.ToTable("CourbDashes");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.ExcelVariable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<int>("LigneFinanciereId")
                        .HasColumnType("integer")
                        .HasColumnName("ligne_financiere_id");

                    b.Property<int?>("SocieteId")
                        .HasColumnType("integer")
                        .HasColumnName("societe_id");

                    b.HasKey("Id");

                    b.HasIndex("LigneFinanciereId")
                        .IsUnique();

                    b.ToTable("ExcelVariables");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.FamilleProduit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Nom")
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.HasKey("Id");

                    b.ToTable("FamillesProduit");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.LigneCalculee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_creation");

                    b.Property<string>("Expression")
                        .HasColumnType("text")
                        .HasColumnName("expression");

                    b.Property<string>("Nom")
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<int?>("RapportFinancierId")
                        .HasColumnType("integer")
                        .HasColumnName("rapport_financier_id");

                    b.Property<double?>("Resultat")
                        .HasColumnType("double precision")
                        .HasColumnName("resultat");

                    b.Property<int>("SocieteId")
                        .HasColumnType("integer")
                        .HasColumnName("societe_id");

                    b.HasKey("Id");

                    b.HasIndex("RapportFinancierId");

                    b.HasIndex("SocieteId");

                    b.ToTable("LignesCalculees");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.LigneFinanciere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Annee")
                        .HasColumnType("integer")
                        .HasColumnName("annee");

                    b.Property<int?>("CrId")
                        .HasColumnType("integer")
                        .HasColumnName("cr_id");

                    b.Property<int>("Mois")
                        .HasColumnType("integer")
                        .HasColumnName("mois");

                    b.Property<double>("Montant")
                        .HasColumnType("double precision")
                        .HasColumnName("montant");

                    b.Property<string>("Nom")
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<int?>("SousCategorieCrId")
                        .HasColumnType("integer")
                        .HasColumnName("sous_categorie_cr_id");

                    b.Property<int>("SousCategorieFinanciereId")
                        .HasColumnType("integer")
                        .HasColumnName("sous_categorie_financiere_id");

                    b.Property<string>("Unite")
                        .HasColumnType("text")
                        .HasColumnName("unite");

                    b.HasKey("Id");

                    b.HasIndex("CrId");

                    b.HasIndex("SousCategorieCrId");

                    b.HasIndex("SousCategorieFinanciereId");

                    b.ToTable("LignesFinancieres");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<double>("CoutMODParHeure")
                        .HasColumnType("double precision")
                        .HasColumnName("cout_mod_par_heure");

                    b.Property<int?>("FamilleProduitId")
                        .HasColumnType("integer")
                        .HasColumnName("famille_produit_id");

                    b.Property<string>("Nom")
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.Property<double>("PoidsPrevu")
                        .HasColumnType("double precision")
                        .HasColumnName("poids_prevu");

                    b.Property<double>("TauxPoids")
                        .HasColumnType("double precision")
                        .HasColumnName("taux_poids");

                    b.Property<double>("TempsGlobal")
                        .HasColumnType("double precision")
                        .HasColumnName("temps_global");

                    b.Property<double>("TpsUnitaire")
                        .HasColumnType("double precision")
                        .HasColumnName("tps_unitaire");

                    b.Property<int?>("TypeClientId")
                        .HasColumnType("integer")
                        .HasColumnName("type_client_id");

                    b.HasKey("Id");

                    b.HasIndex("FamilleProduitId");

                    b.HasIndex("TypeClientId");

                    b.ToTable("Produits");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.RapportFinancier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Annee")
                        .HasColumnType("integer")
                        .HasColumnName("annee");

                    b.Property<int>("SocieteId")
                        .HasColumnType("integer")
                        .HasColumnName("societe_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("SocieteId");

                    b.ToTable("RapportsFinanciers");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.Societe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Adresse")
                        .HasColumnType("text")
                        .HasColumnName("adresse");

                    b.Property<DateTime>("DateAffectation")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_affectation");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_creation");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nom")
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Pays")
                        .HasColumnType("text")
                        .HasColumnName("pays");

                    b.Property<string>("Telephone")
                        .HasColumnType("text")
                        .HasColumnName("telephone");

                    b.Property<string>("Ville")
                        .HasColumnType("text")
                        .HasColumnName("ville");

                    b.HasKey("Id");

                    b.ToTable("Societes");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.SousCategorieCR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategorieCrId")
                        .HasColumnType("integer")
                        .HasColumnName("categorie_cr_id");

                    b.Property<string>("Nom")
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("Id");

                    b.HasIndex("CategorieCrId");

                    b.ToTable("SousCategoriesCR");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.SousCategorieFinanciere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategorieFinanciereId")
                        .HasColumnType("integer")
                        .HasColumnName("categorie_financiere_id");

                    b.Property<string>("Nom")
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.HasKey("Id");

                    b.HasIndex("CategorieFinanciereId");

                    b.ToTable("SousCategoriesFinancieres");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.TypeClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Nom")
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.HasKey("Id");

                    b.ToTable("TypeClients");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.UserSociete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Adresse")
                        .HasColumnType("text")
                        .HasColumnName("adresse");

                    b.Property<DateTime>("DateAffectation")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_affectation");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nom")
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Prenom")
                        .HasColumnType("text")
                        .HasColumnName("prenom");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<int>("SocieteId")
                        .HasColumnType("integer")
                        .HasColumnName("societe_id");

                    b.Property<string>("Telephone")
                        .HasColumnType("text")
                        .HasColumnName("telephone");

                    b.HasKey("Id");

                    b.HasIndex("SocieteId");

                    b.ToTable("UserSocietes");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.CBDash", b =>
                {
                    b.HasOne("Am.ApplicationCore.Domain.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.CR", b =>
                {
                    b.HasOne("Am.ApplicationCore.Domain.Produit", null)
                        .WithMany("CRs")
                        .HasForeignKey("ProduitId");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.CategorieCR", b =>
                {
                    b.HasOne("Am.ApplicationCore.Domain.RapportFinancier", "RapportFinancier")
                        .WithMany("CategoriesCR")
                        .HasForeignKey("RapportFinancierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RapportFinancier");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.CategorieFinanciere", b =>
                {
                    b.HasOne("Am.ApplicationCore.Domain.RapportFinancier", "RapportFinancier")
                        .WithMany("Categories")
                        .HasForeignKey("RapportFinancierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RapportFinancier");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.ClesDeRepartition", b =>
                {
                    b.HasOne("Am.ApplicationCore.Domain.Societe", "Societe")
                        .WithMany("ClesDeRepartition")
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.CountDash", b =>
                {
                    b.HasOne("Am.ApplicationCore.Domain.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.CourbDash", b =>
                {
                    b.HasOne("Am.ApplicationCore.Domain.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.ExcelVariable", b =>
                {
                    b.HasOne("Am.ApplicationCore.Domain.LigneFinanciere", "LigneFinanciere")
                        .WithOne("ExcelVariable")
                        .HasForeignKey("Am.ApplicationCore.Domain.ExcelVariable", "LigneFinanciereId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LigneFinanciere");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.LigneCalculee", b =>
                {
                    b.HasOne("Am.ApplicationCore.Domain.RapportFinancier", "RapportFinancier")
                        .WithMany()
                        .HasForeignKey("RapportFinancierId");

                    b.HasOne("Am.ApplicationCore.Domain.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RapportFinancier");

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.LigneFinanciere", b =>
                {
                    b.HasOne("Am.ApplicationCore.Domain.CR", "Cr")
                        .WithMany("Lignes")
                        .HasForeignKey("CrId");

                    b.HasOne("Am.ApplicationCore.Domain.SousCategorieCR", "SousCategorieCR")
                        .WithMany("Lignes")
                        .HasForeignKey("SousCategorieCrId");

                    b.HasOne("Am.ApplicationCore.Domain.SousCategorieFinanciere", "SousCategorieFinanciere")
                        .WithMany("Lignes")
                        .HasForeignKey("SousCategorieFinanciereId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cr");

                    b.Navigation("SousCategorieCR");

                    b.Navigation("SousCategorieFinanciere");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.Produit", b =>
                {
                    b.HasOne("Am.ApplicationCore.Domain.FamilleProduit", "FamilleProduit")
                        .WithMany("Produits")
                        .HasForeignKey("FamilleProduitId");

                    b.HasOne("Am.ApplicationCore.Domain.TypeClient", "TypeClient")
                        .WithMany("Produits")
                        .HasForeignKey("TypeClientId");

                    b.Navigation("FamilleProduit");

                    b.Navigation("TypeClient");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.RapportFinancier", b =>
                {
                    b.HasOne("Am.ApplicationCore.Domain.Societe", "Societe")
                        .WithMany("RapportsFinanciers")
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.SousCategorieCR", b =>
                {
                    b.HasOne("Am.ApplicationCore.Domain.CategorieCR", "CategorieCR")
                        .WithMany("SousCategories")
                        .HasForeignKey("CategorieCrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategorieCR");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.SousCategorieFinanciere", b =>
                {
                    b.HasOne("Am.ApplicationCore.Domain.CategorieFinanciere", "CategorieFinanciere")
                        .WithMany("SousCategories")
                        .HasForeignKey("CategorieFinanciereId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategorieFinanciere");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.UserSociete", b =>
                {
                    b.HasOne("Am.ApplicationCore.Domain.Societe", "Societe")
                        .WithMany("Users")
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.CR", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.CategorieCR", b =>
                {
                    b.Navigation("SousCategories");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.CategorieFinanciere", b =>
                {
                    b.Navigation("SousCategories");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.FamilleProduit", b =>
                {
                    b.Navigation("Produits");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.LigneFinanciere", b =>
                {
                    b.Navigation("ExcelVariable");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.Produit", b =>
                {
                    b.Navigation("CRs");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.RapportFinancier", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("CategoriesCR");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.Societe", b =>
                {
                    b.Navigation("ClesDeRepartition");

                    b.Navigation("RapportsFinanciers");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.SousCategorieCR", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.SousCategorieFinanciere", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("Am.ApplicationCore.Domain.TypeClient", b =>
                {
                    b.Navigation("Produits");
                });
#pragma warning restore 612, 618
        }
    }
}
